export enum ETableNames {
  empresas = 'empresas',
  usuarios = 'usuarios',
  produtos = 'produtos',
  pedidos = 'pedidos',
  pedido_itens = 'pedido_itens',
  vw_sh_empresas_sinc_config = 'vw_sh_empresas_sinc_config',
  vw_sh_pedidos_sinc = 'vw_sh_pedidos_sinc',
  vw_p4m_empresas_sinc_config = 'vw_p4m_empresas_sinc_config',
  vw_p4m_produtos_sinc = 'vw_p4m_produtos_sinc',
  p4m_canais_vendas = 'p4m_canais_vendas',
  p4m_categorias = 'p4m_categorias',
  p4m_atributos = 'p4m_atributos',
  p4m_produtos = 'p4m_produtos',
}
