import { Knex } from 'knex';

import { ETableNames } from '../eTableNames';
const { NODE_ENV } = process.env;

export const seed = async (knex: Knex) => {
  if (NODE_ENV === 'production') return;

  const result = await knex(ETableNames.p4m_canais_vendas).first();
  if (result) return;

  await knex(ETableNames.p4m_canais_vendas)
    .insert([
      { codigo: 1, cnpj: '15436940000103', nome: 'AMAZON', canal_p4m: true },
      { codigo: 2, cnpj: '33041260199572', nome: 'VIA MARKETPLACE', canal_p4m: true },
      { codigo: 4, cnpj: '47960950000121', nome: 'MAGAZINE LUIZA', canal_p4m: true },
      { codigo: 5, cnpj: '09339936000205', nome: 'NETSHOES', canal_p4m: true },
      { codigo: 6, cnpj: '00776574000660', nome: 'AMERICANAS MARKETPLACE', canal_p4m: true },
      { codigo: 7, cnpj: '03007331000141', nome: 'MERCADO LIVRE', canal_p4m: true },
      { codigo: 8, cnpj: '45543915084695', nome: 'CARREFOUR', canal_p4m: true },
      { codigo: 9, cnpj: '10490181000135', nome: 'MADEIRA MADEIRA', canal_p4m: true },
      { codigo: 10, cnpj: '11200418000592', nome: 'DAFITI', canal_p4m: true },
      { codigo: 11, cnpj: '', nome: 'MAGENTO 1', canal_p4m: true },
      { codigo: 16, cnpj: '89848543001572', nome: 'LOJAS COLOMBO', canal_p4m: true },
      { codigo: 17, cnpj: '', nome: 'CLIMBA COMMERCE', canal_p4m: true },
      { codigo: 18, cnpj: '11428403000152', nome: 'IGUATEMI', canal_p4m: true },
      { codigo: 19, cnpj: '06347409006953', nome: 'CENTAURO', canal_p4m: true },
      { codigo: 20, cnpj: '01438784006561', nome: 'LEROY MERLIN', canal_p4m: true },
      { codigo: 22, cnpj: '26900161000125', nome: 'RAPPI', canal_p4m: true },
      { codigo: 23, cnpj: '', nome: 'WOOCOMMERCE', canal_p4m: true },
      { codigo: 24, cnpj: '', nome: 'VTEX', canal_p4m: true },
      { codigo: 25, cnpj: '', nome: 'TRAY', canal_p4m: true },
      { codigo: 26, cnpj: '35635824000112', nome: 'SHOPEE', canal_p4m: true },
      { codigo: 27, cnpj: '45242914000105', nome: 'C&A', canal_p4m: true },
      { codigo: 28, cnpj: '61585865024093', nome: 'DROGASIL', canal_p4m: true },
      { codigo: 29, cnpj: '', nome: 'ISET', canal_p4m: true },
      { codigo: 30, cnpj: '', nome: 'NOVO MUNDO', canal_p4m: true },
      { codigo: 31, cnpj: '', nome: 'LOJAINTEGRADA', canal_p4m: true },
      { codigo: 32, cnpj: '', nome: 'MAGENTO 2', canal_p4m: true },
      { codigo: 33, cnpj: '92754738000162', nome: 'RENNER', canal_p4m: true },
      { codigo: 34, cnpj: '33200056000149', nome: 'RIACHUELO', canal_p4m: true },
      { codigo: 35, cnpj: '', nome: 'CWS', canal_p4m: true },
      { codigo: 36, cnpj: '18552346000168', nome: 'OLIST', canal_p4m: true },
      { codigo: 37, cnpj: '75400218000132', nome: 'CASSOL', canal_p4m: true },
      { codigo: 38, cnpj: '', nome: 'TRAY COMMERCE', canal_p4m: true },
      { codigo: 39, cnpj: '', nome: 'LINX', canal_p4m: true },
      { codigo: 40, cnpj: '', nome: 'CASA VIDEO', canal_p4m: true },
      { codigo: 41, cnpj: '02314041002202', nome: 'DECATHLON', canal_p4m: true },
      { codigo: 42, cnpj: '', nome: 'GRUPO SOMA', canal_p4m: true },
      { codigo: 43, cnpj: '', nome: 'MULTIFAST', canal_p4m: true },
      { codigo: 44, cnpj: '', nome: 'ORTOBOM', canal_p4m: true },
      { codigo: 45, cnpj: '', nome: 'VERTEM', canal_p4m: true },
      { codigo: 46, cnpj: '61585865024093', nome: 'RDMARKETPLACE', canal_p4m: true },
      { codigo: 47, cnpj: '', nome: 'COOPERA', canal_p4m: true },
      { codigo: 48, cnpj: '', nome: 'RESERVA', canal_p4m: true },
      { codigo: 49, cnpj: '', nome: 'SHOPHUB', canal_p4m: true },
      { codigo: 50, cnpj: '', nome: 'LOJAS MM', canal_p4m: true },
      { codigo: 51, cnpj: '', nome: 'MESBLA', canal_p4m: true },
      { codigo: 52, cnpj: '', nome: 'CONECTALA', canal_p4m: true },
      { codigo: 53, cnpj: '', nome: 'POLISHOP', canal_p4m: true },
      { codigo: 54, cnpj: '', nome: 'B4C', canal_p4m: true },
      { codigo: 55, cnpj: '', nome: 'BALAROTI', canal_p4m: true },
      { codigo: 56, cnpj: '', nome: 'CJFASHION', canal_p4m: true },
      { codigo: 57, cnpj: '', nome: 'CONNECTPARTS', canal_p4m: true },
      { codigo: 58, cnpj: '', nome: 'FIBRACIRURGICA', canal_p4m: true },
      { codigo: 59, cnpj: '', nome: 'KEEPRUNNING', canal_p4m: true },
      { codigo: 60, cnpj: '', nome: 'PANGEIA', canal_p4m: true },
      { codigo: 61, cnpj: '', nome: 'OFFPREMIUM', canal_p4m: true },
      { codigo: 62, cnpj: '', nome: 'SHOPPING CALCADO', canal_p4m: true },
      { codigo: 63, cnpj: '', nome: 'SICREDI', canal_p4m: true },
      { codigo: 64, cnpj: '', nome: 'ALIEXPRESS', canal_p4m: true },
      { codigo: 66, cnpj: '', nome: 'SIMPLO7', canal_p4m: true },
      { codigo: 67, cnpj: '03002339000115', nome: 'CAMICADO', canal_p4m: true },
      { codigo: 68, cnpj: '', nome: 'F1 COMMERCE', canal_p4m: true },
      { codigo: 69, cnpj: '', nome: 'MKX', canal_p4m: true },
      { codigo: 70, cnpj: '', nome: 'NUVEMSHOP', canal_p4m: true },
      { codigo: 71, cnpj: '', nome: 'FLEXY', canal_p4m: true },
      { codigo: 72, cnpj: '', nome: 'MAGAZORD', canal_p4m: true },
      { codigo: 73, cnpj: '', nome: 'TINY', canal_p4m: true },
      { codigo: 74, cnpj: '45814425000172', nome: 'SHEIN', canal_p4m: true },
      { codigo: 75, cnpj: '', nome: 'FARMADELIVERY', canal_p4m: true },
      { codigo: 76, cnpj: '', nome: 'VNDA', canal_p4m: true },
      { codigo: 77, cnpj: '', nome: 'ZEMA', canal_p4m: true },
      { codigo: 78, cnpj: '', nome: 'SICOOB', canal_p4m: true },
      { codigo: 79, cnpj: '', nome: 'VIAWEAR', canal_p4m: true },
      { codigo: 80, cnpj: '', nome: 'CENTRO FASHION', canal_p4m: true },
      { codigo: 81, cnpj: '', nome: 'PASSARELA', canal_p4m: true },
      { codigo: 82, cnpj: '', nome: 'SHOP DOS CABELOS', canal_p4m: true },
      { codigo: 83, cnpj: '10464223000163', nome: 'PRIVALIA', canal_p4m: true },
      { codigo: 84, cnpj: '', nome: 'VTEX B2B', canal_p4m: true },
      { codigo: 85, cnpj: '', nome: 'KROOZE', canal_p4m: true },
      { codigo: 86, cnpj: '80462138000141', nome: 'POSTHAUS', canal_p4m: true },
      { codigo: 87, cnpj: '', nome: 'WOOCOMMERCE B2B', canal_p4m: true },
      { codigo: 88, cnpj: '', nome: 'RAMARIM', canal_p4m: true },
      { codigo: 89, cnpj: '', nome: 'LEBISCUIT', canal_p4m: true },
      { codigo: 90, cnpj: '', nome: 'OSCAR CALCADOS', canal_p4m: true },
      { codigo: 91, cnpj: '', nome: 'ANGELONI', canal_p4m: true },
      { codigo: 92, cnpj: '', nome: 'CONFORTFLEX', canal_p4m: true },
      { codigo: 93, cnpj: '', nome: 'VENTURESHOP', canal_p4m: true },
      { codigo: 94, cnpj: '', nome: 'PITSTOP', canal_p4m: true },
      { codigo: 95, cnpj: '', nome: 'BELGO', canal_p4m: true },
      { codigo: 96, cnpj: '', nome: 'DORMED', canal_p4m: true },
      { codigo: 97, cnpj: '', nome: 'BABYBIZ', canal_p4m: true },
      { codigo: 2320, cnpj: '', nome: 'PONTO DE VENDAS', canal_p4m: true },
      { codigo: 98, cnpj: '08584116000712', nome: 'WEBCONTINENTAL', canal_p4m: true },
      { codigo: 101, cnpj: '', nome: 'GRUPO ITAPUA', canal_p4m: true },
      { codigo: 15, cnpj: '', nome: 'FASTSHOP', canal_p4m: true },
      { codigo: 104, cnpj: '', nome: 'ARAMIS', canal_p4m: true },
      { codigo: 105, cnpj: '', nome: 'EPOCA COSMETICOS', canal_p4m: true },
      { codigo: 106, cnpj: '', nome: 'MATEUS MAIS', canal_p4m: true },
      { codigo: 107, cnpj: '', nome: 'NA TERRA', canal_p4m: true },
      { codigo: 108, cnpj: '', nome: 'RIHAPPY', canal_p4m: true },
      { codigo: 111, cnpj: '', nome: 'MARISOL', canal_p4m: true },
    ])
    .then(() => {
      console.log(`# Inserido dados na tabela ${ETableNames.p4m_canais_vendas}`);
    });
};
