import { Knex } from 'knex';

import { ETableNames } from '../eTableNames';
const { NODE_ENV } = process.env;

export const seed = async (knex: Knex) => {
  if (NODE_ENV === 'production') return;

  const result = await knex(ETableNames.empresa_canais).first();
  if (result) return;

  await knex(ETableNames.empresa_canais)
    .insert([
      { empresa_id: 1, canal_codigo: 1 },
      { empresa_id: 1, canal_codigo: 2 },
      { empresa_id: 1, canal_codigo: 4 },
      { empresa_id: 1, canal_codigo: 5 },
      { empresa_id: 1, canal_codigo: 6 },
      { empresa_id: 1, canal_codigo: 7 },
      { empresa_id: 1, canal_codigo: 8 },
      { empresa_id: 1, canal_codigo: 9 },
      { empresa_id: 1, canal_codigo: 10 },
      { empresa_id: 1, canal_codigo: 11 },
      { empresa_id: 1, canal_codigo: 16 },
      { empresa_id: 1, canal_codigo: 17 },
      { empresa_id: 1, canal_codigo: 18 },
      { empresa_id: 1, canal_codigo: 19 },
      { empresa_id: 1, canal_codigo: 20 },
      { empresa_id: 1, canal_codigo: 22 },
      { empresa_id: 1, canal_codigo: 23 },
      { empresa_id: 1, canal_codigo: 24 },
      { empresa_id: 1, canal_codigo: 25 },
      { empresa_id: 1, canal_codigo: 26 },
      { empresa_id: 1, canal_codigo: 27 },
      { empresa_id: 1, canal_codigo: 28 },
      { empresa_id: 1, canal_codigo: 29 },
      { empresa_id: 1, canal_codigo: 30 },
      { empresa_id: 1, canal_codigo: 31 },
      { empresa_id: 1, canal_codigo: 32 },
      { empresa_id: 1, canal_codigo: 33 },
      { empresa_id: 1, canal_codigo: 34 },
      { empresa_id: 1, canal_codigo: 35 },
      { empresa_id: 1, canal_codigo: 36 },
      { empresa_id: 1, canal_codigo: 37 },
      { empresa_id: 1, canal_codigo: 38 },
      { empresa_id: 1, canal_codigo: 39 },
      { empresa_id: 1, canal_codigo: 40 },
      { empresa_id: 1, canal_codigo: 41 },
      { empresa_id: 1, canal_codigo: 42 },
      { empresa_id: 1, canal_codigo: 43 },
      { empresa_id: 1, canal_codigo: 44 },
      { empresa_id: 1, canal_codigo: 45 },
      { empresa_id: 1, canal_codigo: 46 },
      { empresa_id: 1, canal_codigo: 47 },
      { empresa_id: 1, canal_codigo: 48 },
      { empresa_id: 1, canal_codigo: 49 },
      { empresa_id: 1, canal_codigo: 50 },
      { empresa_id: 1, canal_codigo: 51 },
      { empresa_id: 1, canal_codigo: 52 },
      { empresa_id: 1, canal_codigo: 53 },
      { empresa_id: 1, canal_codigo: 54 },
      { empresa_id: 1, canal_codigo: 55 },
      { empresa_id: 1, canal_codigo: 56 },
      { empresa_id: 1, canal_codigo: 57 },
      { empresa_id: 1, canal_codigo: 58 },
      { empresa_id: 1, canal_codigo: 59 },
      { empresa_id: 1, canal_codigo: 60 },
      { empresa_id: 1, canal_codigo: 61 },
      { empresa_id: 1, canal_codigo: 62 },
      { empresa_id: 1, canal_codigo: 63 },
      { empresa_id: 1, canal_codigo: 64 },
      { empresa_id: 1, canal_codigo: 66 },
      { empresa_id: 1, canal_codigo: 67 },
      { empresa_id: 1, canal_codigo: 68 },
      { empresa_id: 1, canal_codigo: 69 },
      { empresa_id: 1, canal_codigo: 70 },
      { empresa_id: 1, canal_codigo: 71 },
      { empresa_id: 1, canal_codigo: 72 },
      { empresa_id: 1, canal_codigo: 73 },
      { empresa_id: 1, canal_codigo: 74 },
      { empresa_id: 1, canal_codigo: 75 },
      { empresa_id: 1, canal_codigo: 76 },
      { empresa_id: 1, canal_codigo: 77 },
      { empresa_id: 1, canal_codigo: 78 },
      { empresa_id: 1, canal_codigo: 79 },
      { empresa_id: 1, canal_codigo: 80 },
      { empresa_id: 1, canal_codigo: 81 },
      { empresa_id: 1, canal_codigo: 82 },
      { empresa_id: 1, canal_codigo: 83 },
      { empresa_id: 1, canal_codigo: 84 },
      { empresa_id: 1, canal_codigo: 85 },
      { empresa_id: 1, canal_codigo: 86 },
      { empresa_id: 1, canal_codigo: 87 },
      { empresa_id: 1, canal_codigo: 88 },
      { empresa_id: 1, canal_codigo: 89 },
      { empresa_id: 1, canal_codigo: 90 },
      { empresa_id: 1, canal_codigo: 91 },
      { empresa_id: 1, canal_codigo: 92 },
      { empresa_id: 1, canal_codigo: 93 },
      { empresa_id: 1, canal_codigo: 94 },
      { empresa_id: 1, canal_codigo: 95 },
      { empresa_id: 1, canal_codigo: 96 },
      { empresa_id: 1, canal_codigo: 97 },
      { empresa_id: 1, canal_codigo: 2320 },
      { empresa_id: 1, canal_codigo: 98 },
      { empresa_id: 1, canal_codigo: 101 },
      { empresa_id: 1, canal_codigo: 15 },
      { empresa_id: 1, canal_codigo: 104 },
      { empresa_id: 1, canal_codigo: 105 },
      { empresa_id: 1, canal_codigo: 106 },
      { empresa_id: 1, canal_codigo: 107 },
      { empresa_id: 1, canal_codigo: 108 },
      { empresa_id: 1, canal_codigo: 111 },
    ])
    .then(() => {
      console.log(`# Inserido dados na tabela ${ETableNames.empresa_canais}`);
    });
};
